version: '3.8'

services:
  frontend:
    container_name: threadly-frontend
    image: threadly-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - BACKEND_BASE_URL=http://threadly-backend.manjurulhoque.com
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://threadly.manjurulhoque.com
    restart: unless-stopped
    networks:
        - threadly-network
    volumes:
        - threadly-frontend-data:/data

  nginx:
    container_name: threadly-frontend-nginx
    image: threadly-frontend-nginx
    build: ./deployment/nginx
    ports:
      - "81:80"
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
        - threadly-network
networks:
    threadly-network:
volumes:
    threadly-frontend-data:
